name: Run pre-commit

run-name: ${{ github.workflow }} for ${{ github.ref_name }}

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run pre-commit
        uses: zeevro/action-pre-commit-uv@main # TODO: Replace with tox-dev/action-pre-commit-uv once PR is merged

  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    env:
      COVERAGE_FILE: coverage-python${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: pyproject.toml
          python-version: ${{ matrix.python-version }}

      - run: uv run pytest -vv --cov

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.COVERAGE_FILE }}
          path: ${{ env.COVERAGE_FILE }}
          if-no-files-found: error

  report-coverage:
    runs-on: ubuntu-latest

    needs: [unit-tests]

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'

      - uses: actions/download-artifact@v4
        with:
          pattern: coverage-python*
          merge-multiple: true

      - run: uvx coverage combine coverage-python*

      - run: uvx coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
